name: build-and-deploy-dev

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pull-requests: write

jobs:
  build_push_and_pr_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push (tag=commit SHA) and capture digest
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/app:${{ github.sha }}

      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y yq

      - name: Checkout Manifest Repo
        uses: actions/checkout@v4
        with:
          repository: Sandeshsanthu/artifact-promotion-deployment.git
          path: manifest-repo # This puts the manifests in a sub-folder
          token: ${{ secrets.GITOPS_PAT }} # Needs a Personal Access Token with repo scope

      - name: Update overlays/dev to the pushed digest
        run: |
          DIGEST="${{ steps.build.outputs.digest }}"
          FILE="overlays/dev/kustomization.yaml"
          IMAGE_NAME="${{ vars.DOCKERHUB_USERNAME }}/app"

          echo "Pushed digest: ${DIGEST}"
          
          # Check if file exists
          if [ ! -f "$FILE" ]; then
             echo "Error: $FILE not found!"
            exit 1
          fi

          # Use yq to update the digest and name. 
          # We use env variables to safely pass values into the yq expression.
          # This removes the need for complex nested quoting.
          IMAGE_NAME="$IMAGE_NAME" NEW_DIGEST="$DIGEST" yq -i '
            .images[] |= select(.name == "app-image") |= (
              .newName = env(IMAGE_NAME) | 
              .digest = env(NEW_DIGEST) | 
              del(.newTag)
            )
          ' "$FILE"

          git diff -- "$FILE"