name: build-and-deploy-dev

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pull-requests: write

jobs:
  build_push_and_pr_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push (tag=commit SHA) and capture digest
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/app:${{ github.sha }}


      - name: Checkout Manifest Repo
        uses: actions/checkout@v4
        with:
          repository: Sandeshsanthu/artifact-promotion-deployment.git
          path: manifest-repo # This puts the manifests in a sub-folder
          token: ${{ secrets.GITOPS_PAT }} # Needs a Personal Access Token with repo scope
          ref: main
      
      - name: Install yq (v4)
        uses: mikefarah/yq@v4

      - name: Update overlays/dev to the pushed digest
        shell: bash
        run: |
          set -euo pipefail

          DIGEST="${{ steps.build.outputs.digest }}"
          FILE="manifest-repo/overlays/dev/kustomization.yaml"
          IMAGE_NAME="${{ vars.DOCKERHUB_USERNAME }}/app"

          echo "Pushed digest: ${DIGEST}"
          test -f "$FILE" || { echo "Missing $FILE"; ls -R manifest-repo; exit 1; }

          yq e '.' "$FILE" >/dev/null

          IMAGE_NAME="$IMAGE_NAME" NEW_DIGEST="$DIGEST" yq -i '
            (.images[] | select(.name == "app-image")) |= (
              .newName = env(IMAGE_NAME) |
              .digest  = env(NEW_DIGEST) |
              del(.newTag)
            )
          ' "$FILE"

          cd manifest-repo
          git diff -- "overlays/dev/kustomization.yaml" || true

          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add "overlays/dev/kustomization.yaml"

          if git diff --cached --quiet; then
            echo "No manifest changes to commit."
            exit 0
          fi

          git commit -m "dev: update app image digest to ${DIGEST}"
          git push origin main
